---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 15m
  values:
    fullnameOverride: renovate-operator
    route:
      enabled: true
      hostnames:
        - renovate.oxygn.dev
      parentRefs:
        - name: envoy-internal
          namespace: network
    webhook:
      enabled: true
