---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugin-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: intel-device-plugin-operator
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: intel-device-plugin-operator
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/kube-system/intel-device-plugin-operator/app
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  wait: true
---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: intel-device-plugin-gpu
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: intel-device-plugin-gpu
  dependsOn:
    - name: intel-device-plugin-operator
      namespace: kube-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: intel-device-plugin-gpu
      namespace: kube-system
    - apiVersion: deviceplugin.intel.com/v1
      kind: GpuDevicePlugin
      name: i915
  healthCheckExprs:
    - apiVersion: deviceplugin.intel.com/v1
      kind: GpuDevicePlugin
      failed: status.desiredNumberScheduled != status.numberReady
      current: status.desiredNumberScheduled == status.numberReady
  interval: 1h
  path: ./kubernetes/apps/kube-system/intel-device-plugin-operator/gpu
  prune: true
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  wait: false
