---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml

# configMapGenerator:
#   - name: qbittorrent-coredns
#     files:
#       - ./config/Corefile
# generatorOptions:
#   annotations:
#     kustomize.toolkit.fluxcd.io/substitute: disabled
# configurations:
#   - kustomizeconfig.yaml
