---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: 10.10.98.0/24
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgpadvertisement_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: l3-bgp-advertisement
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - {key: somekey, operator: NotIn, values: ["never-used-value"]}
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgppeerconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: l3-bgp-peer-config
spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumbgpclusterconfig_v2.json
apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: l3-bgp-cluster-config
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  bgpInstances:
    - name: cilium
      localASN: 64514
      peers:
        - name: unifi
          peerASN: 64513
          peerAddress: 10.10.0.1
          peerConfigRef:
            name: l3-bgp-peer-config
---
apiVersion: v1
kind: Service
metadata:
  name: kube-api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: k8s.oxygn.dev
    lbipam.cilium.io/ips: 10.10.98.254
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - port: 6443

# ---
# # yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
# apiVersion: cilium.io/v2alpha1
# kind: CiliumL2AnnouncementPolicy
# metadata:
#   name: l2-policy
# spec:
#   loadBalancerIPs: true
#   interfaces: ["^bond.*"]
#   nodeSelector:
#     matchLabels:
#       kubernetes.io/os: linux
# ---
# # yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/cilium.io/ciliumbgpadvertisement_v2alpha1.json
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumBGPAdvertisement
# metadata:
#   name: cilium-bgp-advertisement
#   labels:
#     advertise: bgp
# spec:
#   advertisements:
#     # - advertisementType: "PodCIDR"
#     - advertisementType: "Service"
#       service:
#         addresses:
#           - LoadBalancerIP
#       selector:
#         matchExpressions:
#           - { key: somekey, operator: NotIn, values: ["never-used-value"] }
# ---
# # yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/cilium.io/ciliumbgppeerconfig_v2alpha1.json
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumBGPPeerConfig
# metadata:
#   name: cilium-bgp-peer-config-ipv4
# spec:
#   families:
#     - afi: ipv4
#       safi: unicast
#       advertisements:
#         matchLabels:
#           advertise: "bgp"
# ---
# # yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/cilium.io/ciliumbgpclusterconfig_v2alpha1.json
# apiVersion: "cilium.io/v2alpha1"
# kind: CiliumBGPClusterConfig
# metadata:
#   name: cilium-bgp-cluster-config
# spec:
#   nodeSelector:
#     matchLabels:
#       kubernetes.io/os: linux
#   bgpInstances:
#     - name: "udm-pro-64514"
#       localASN: 64514
#       peers:
#         - name: "peer-64513-ipv4"
#           peerASN: 64513
#           peerAddress: "10.10.0.1"
#           peerConfigRef:
#             name: "cilium-bgp-peer-config-ipv4"
# ---
# # yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/cilium.io/ciliumloadbalancerippool_v2alpha1.json
# apiVersion: cilium.io/v2alpha1
# kind: CiliumLoadBalancerIPPool
# metadata:
#   name: lb-pool
# spec:
#   allowFirstLastIPs: "Yes"
#   blocks:
#     - start: 10.10.98.100
#       stop: 10.10.98.254
