---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flaresolverr
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: flaresolverr
  interval: 1h
  path: ./kubernetes/apps/download/flaresolverr/app
  postBuild:
    substitute:
      APP: flaresolverr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: download
  wait: false
