---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flaresolverr
  namespace: download
spec:
  interval: 1h
  path: ./kubernetes/apps/download/flaresolverr/app
  postBuild:
    substitute:
      APP: flaresolverr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: download
  wait: false
