---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: openebs
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: openebs
      namespace: openebs-system
  interval: 1h
  path: ./kubernetes/apps/openebs-system/openebs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  retryInterval: 2m
  targetNamespace: openebs-system
  wait: true
