---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: dragonfly
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: dragonfly
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/dragonfly/app
  postBuild:
    substitute:
      APP: dragonfly
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  retryInterval: 2m
  targetNamespace: database
  wait: true

---
# yaml-language-server: $schema=https://k8s-schemas.oxygn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-cluster
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: dragonfly-cluster
  dependsOn:
    - name: dragonfly
      namespace: database
  interval: 1h
  path: ./kubernetes/apps/database/dragonfly/cluster
  postBuild:
    substitute:
      APP: dragonfly-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: false
