---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
kind: Kustomization
namespace: automation
components:
  - ../../components/alerts

resources:
  - ./namespace.yaml
  - ./home-assistant/ks.yaml
  - ./teslamate/ks.yaml
  - ./mosquitto/ks.yaml
